server:
  port: 8101
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xiaolu991954992/config-repo/
          username: xiaolu991954992
          password: xiaolu789sxl
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/